### ISSUE TITLE
Support for Shapely 2 immutable geometries

### ISSUE THREAD

**Issue by tfardet** [SENeC-Initiative/PyNCulture#33]
With v2, Shapely completely broke inheritance from geometry objects.
I'm going to adapt the Shape object based on [this post](https://github.com/shapely/shapely/issues/1233#issuecomment-1034324441) to keep our inheritance support, but this means that Shapely > 2 will be a hard requirement as it would be too complicated to support the old and new versions.

**Comment by aanastasiou** [comment]
@tfardet Could I please ask what is the status of this? I reached this issue after 4-5 posts detailing what the problem (I am facing too) is, but subclassing a Shapely Point is still behaving "unexpectedly" on Shapely 2.0.1.

(At the moment, the only viable solution seems to create a complete adadpter of the Shapely Point rather than compose it via inheritance, but this is not exactly the same)

**Comment by tfardet** [comment]
It's all in PR #34: I set the slots and used a dict to replace normal attributes

**Comment by aanastasiou** [comment]
Thanks for your response @tfardet, there does not seem to be another way unfortunately...
